name: Handle GitLab CI/CD

on:
  workflow_dispatch:
    inputs:
      payload:
        type: string
        required: true

jobs:
  init:
    runs-on: ubuntu-latest

    name: Hello

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6

      - name: Log
        run: |
          echo "${{ github.event.inputs.payload }}"
